version: "3"

services:
  bookstore:
    build: .
    image: bookstore-api
    ports:
      - "3000:3000"
    links:
      - "db:database"
    env_file:
    - docker.env
  db:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"